Fully translated CommonEvents.json
Creta5164/causality-demo-l10n pull request #5
Opened 2020-09-08 16:15 UTC by BladeSides

2020-09-08 19:34 UTC, Creta5164 requested changes
Most of them is nicely done, but there's something have problem.  
I wrote the mistranslated contents and the problematic parts here, so please correct them.

2020-09-08 19:34 UTC, Creta5164 commented on en/CommonEvents.json
> +            "but it did nothing."
This is selection dialogue that means 'Put a book in the shelf' and 'Do noting'.

2020-09-08 19:34 UTC, Creta5164 commented on en/CommonEvents.json
> +        "\\!Some guy kicked cause he was slow.",
미친놈 is means like 'crazy person' like thing.

2020-09-08 19:34 UTC, Creta5164 commented on en/CommonEvents.json
> +        "Obtained the health room key."
그러나 is does like 'but', is there reason to wrote like this?

2020-09-08 19:34 UTC, Creta5164 commented on en/CommonEvents.json
> +        "There's a \\C[2]black hand\\C[0]guy.",
Use 'ghost' instead 'guy' or use more effective word if you have suggest us.

2020-09-08 19:34 UTC, Creta5164 commented on en/CommonEvents.json
> +        "I'll tell you what I know!"
Change ! to . because this word is spoken by character that serious person.

2020-09-08 19:34 UTC, Creta5164 commented on en/CommonEvents.json
> +        "I call it the \\C[1]ghost phenomenon\\C[0].",
폴터가이스트 is means Poltergeist, use this word instead ghost phenomenon after of it.

2020-09-08 19:34 UTC, Creta5164 commented on en/CommonEvents.json
> +        "\\!Just try to get out of there.",
This paragraph is also separated.  
It's looks like this :  
>이상한 소리가 들리면서 말도 안 되는 현상이 나타난다면 그냥 그곳을 최대한 벗어나려고 해봐.

2020-09-08 19:34 UTC, Creta5164 commented on en/CommonEvents.json
> +        "I'm doing a trick.",
This paragraph is separated, it's looks like this :
> 잔챙이 놈들이 모습을 감추고 수작질을 부리는 거지.

잔챙이 is means 'small fry' according [here](https://en.dict.naver.com/#/entry/koen/8aa8386ae3144d2eaaef71a347ab7b75)  
Is there reason to wrote like this?

2020-09-08 20:00 UTC, Creta5164 requested changes
Someone have reviewed more paragraphs, please check them.

2020-09-08 20:00 UTC, Creta5164 commented on en/CommonEvents.json
> +        "Good news!",
Someone suggested to change to 'That's good news.'.

2020-09-08 20:00 UTC, Creta5164 commented on en/CommonEvents.json
> +        "Wonder if it's the same place",
Someone suggested to change to 'Wonder if it's in the same place'

2020-09-08 20:00 UTC, Creta5164 commented on en/CommonEvents.json
> +        "...Did you see the shadow?",
Someone suggested to change to 'Did you see that shadow?'

2020-09-08 20:00 UTC, Creta5164 commented on en/CommonEvents.json
> +        "\\!Some guy kicked cause he was slow.",
Someone suggested change to 'Some crazy guys must have kicked the computer because it was so slow'

2020-09-08 20:00 UTC, Creta5164 commented on en/CommonEvents.json
> +        "\\!Some guy kicked cause he was slow.",
Also some more people suggested change to :
> Well, let's see.
> ...Huh, this wire was pulled again.
> Maybe some crazy guy kicked up this computer again to get faster.

2020-09-09 03:47 UTC, BladeSides commented on en/CommonEvents.json
> +        "Obtained the health room key."
The but seems unnecessary, although I added it again.

2020-09-09 03:55 UTC, BladeSides commented
Updated as requested.

2020-09-09 04:34 UTC, Creta5164 commented
I updated standalone demo, because I recently found some glitch happens in another language.  
So please download it and take to look them in-game!

I requested to reviewing this to another person about text only and in-game of this PR.  
Then we found silly things and bunch of outlandish situations while checking this.  

These common event content can found in `menu-phone call` and `use key items`.

2020-09-09 06:14 UTC, BladeSides commented
Will add another pull request after improving quality of translation.

2020-09-09 06:14 UTC, closed without merging